CREATE TABLE [dbo].[TDRA_DRUGAMOUNT]
(
[DRA_ID] [int] NOT NULL IDENTITY(1, 1),
[DRA_BOTTOMAMOUNT] [decimal] (18, 5) NULL,
[DRA_TOPAMOUNT] [decimal] (18, 5) NULL,
[UNI_ID] [int] NOT NULL,
[DRA_DCF] [int] NOT NULL,
[DRA_LASTUPD] [datetime] NULL,
[DRA_LASTUPDBY] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROWID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TDRA_DRUG__ROWID__6C5905DD] DEFAULT (newid()),
[DRA_CREATED_DATE] [datetime] NULL,
[DRA_CREATED_BY] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TDRA_DRUGAMOUNT] ADD CONSTRAINT [Drum_Amount_Key] PRIMARY KEY CLUSTERED ([DRA_ID]) ON [PRIMARY]
GO
